AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'config/deploy'
    - 'config/deploy/*'
    - 'config/environments/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'public/uploads/**/**/**/*'
    - 'config/spring.rb'
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Layout/EmptyLines:
  Exclude:
      - 'config/environments/*'
      - 'config/initializers/*'

Metrics/LineLength:
  Max: 130

Metrics/BlockLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
